### PR TITLE
Remove CTIR and FSTBHC.

### PR DESCRIPTION
**Pull request by mbarbar**
Will this run in CI? I don't have things set up to run locally to test.

### CODE REVIEW

**Comment by yuleisui** [comment]
> Will this run in CI? I don't have things set up to run locally to test.

We need to remove anything related to TBHC

**Comment by yuleisui** [comment]
Can you double check before I merge?

**Comment by mbarbar** [comment]
```
mbarbar@alder ~/clone/Test-Suite % ag ctir
mbarbar@alder ~/clone/Test-Suite % ag tbhc
mbarbar@alder ~/clone/Test-Suite %
```

**Comment by yuleisui** [comment]
> mbarbar@alder ~/clone/Test-Suite % ag ctir
> mbarbar@alder ~/clone/Test-Suite % ag tbhc
> mbarbar@alder ~/clone/Test-Suite %

Yes, good, you can push to SVF once this test suits all generated and push to Test-Suite for SVF to download.

**Comment by mbarbar** [comment]
So I push to SVF, then what do I push here?

**Comment by yuleisui** [comment]
> So I push to SVF, then what do I push here?

No, sorry I mean your pull request. Also remember to remove the TBHC options in Options.cpp and the TBHC pointer analysis type in SVF.

**Comment by mbarbar** [comment]
Ah okay.

Yes they're removed.

**Comment by yuleisui** [comment]
Perfect

**Pull request merged**
