### PR TITLE
Shorten CMakeLists, create C++ script for differential testing

### PR DESCRIPTION
**Pull request by lukekoko**
- Now using for loops in CMakeLists (reduced lines to 86 compared to 1000+)
- Removed `generate_cmake_test.sh` as not needed anymore
- Created C++ script to do differential testing

### CODE REVIEW

**Comment by lukekoko** [comment]
Some testcases fail
image

**Comment by lukekoko** [comment]
The differential analysis for fspta-vfspta and ander-nander are in. fspta-vfspta have no errors. ander-nander 2 test cases have errors.

**Comment by yuleisui** [comment]
> The differential analysis for fspta-vfspta and ander-nander are in. fspta-vfspta have no errors. ander-nander 2 test cases have errors.

I saw 28 errors?

**Comment by lukekoko** [comment]
For example this is a test of `wpa -ander -stat=false` that fails
image

**Comment by yuleisui** [comment]
> For example this is a test of `wpa -ander -stat=false` that fails
> image

Strange..
It was correct for the recent commit in main repo. Can you take a look?

https://travis-ci.org/github/SVF-tools/SVF/jobs/769922964#L10761-L10771

**Comment by lukekoko** [comment]
> 
> 
> > For example this is a test of `wpa -ander -stat=false` that fails
> > image
> 
> Strange..
> It was correct for the recent commit in main repo. Can you take a look?
> 
> https://travis-ci.org/github/SVF-tools/SVF/jobs/769922964#L10761-L10771

For this one the test is missing -ff-eq-base=false. I'll add this in

**Comment by yuleisui** [comment]
> > > For example this is a test of `wpa -ander -stat=false` that fails
> > > image
> > 
> > 
> > Strange..
> > It was correct for the recent commit in main repo. Can you take a look?
> > https://travis-ci.org/github/SVF-tools/SVF/jobs/769922964#L10761-L10771
> 
> For this one the test is missing -ff-eq-base=false. I'll add this in

OK

**Comment by yuleisui** [comment]
> > > > For example this is a test of `wpa -ander -stat=false` that fails
> > > > image
> > > 
> > > 
> > > Strange..
> > > It was correct for the recent commit in main repo. Can you take a look?
> > > https://travis-ci.org/github/SVF-tools/SVF/jobs/769922964#L10761-L10771
> > 
> > 
> > For this one the test is missing -ff-eq-base=false. I'll add this in
> 
> OK

How about the other failed tests? Can you list them here? We can check one by one.

**Comment by lukekoko** [comment]
image

**Comment by lukekoko** [comment]
image

image

image

image

image

**Comment by lukekoko** [comment]
> 
> 
> Maybe we create a folder to store those CPP_Failed cases. For memory leak cases, we may not include any of them for now.

Ok, I'll move the failed tests to a failed folder and exclude the memory leak tests

**Comment by yuleisui** [comment]
I assume that after this patch, SVF will still pass all the test cases in CMakeList?

**Pull request merged**
